services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    stdin_open: true
    tty: true
    hostname: oop-course-projects-devctr
    container_name: oop-course-projects-devctr
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity